[package]
name = "aes_cbc"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
csv = "1.1"
rusqlite = "0.26"
memory-stats = "1.2.0"  # Update to the latest version
tokio = { version = "1", features = ["full"] }
