name: Rust CI/CD Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          override: true
    - name: Update Linux
      run: sudo apt update 
    - name: Update Rust
      run: make install
    - name: Check Rust versions
      run: make rust-version
    - name: Format
      run: make format
    - name: Lint
      run: make lint
    - name: Test
      run: make test
    - name: Pull Repository
      run: git pull
    - name: Write Logs
      run: make run   
    - name: Add Rust Logs
      run: make generate_and_push
    - name: Build Release
      run: cargo build --release
    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v3
      with:
        name: rust-binary
        path: target/release/binary_file
